DDS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('records.urls')),
]

records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from records.views import *

urlpatterns = [
    path('purposes/', RecordPurposeListView.as_view(), name='purposes'),
    path('purposes/create', RecordPurposeCreateView.as_view(), name='purpose-create'),
    path('purposes/delete/<int:pk>/', RecordPurposeDeleteView.as_view(), name='purpose-delete'),
    path('purposes/update/<int:pk>/', RecordPurposeUpdateView.as_view(), name='purpose-update'),

    path('types/', RecordTypeListView.as_view(), name='types'),
    path('types/create', RecordTypeCreateView.as_view(), name='type-create'),
    path('types/delete/<int:pk>/', RecordTypeDeleteView.as_view(), name='type-delete'),
    path('types/update/<int:pk>/', RecordTypeUpdateView.as_view(), name='type-update'),

    path('categories/', RecordCategoryListView.as_view(), name='categories'),
    path('categories/create', RecordCategoryCreateView.as_view(), name='category-create'),
    path('categories/delete/<int:pk>/', RecordCategoryDeleteView.as_view(), name='category-delete'),
    path('categories/update/<int:pk>/', RecordCategoryUpdateView.as_view(), name='category-update'),

    path('subcategories/<int:category_id>', RecordSubCategoryListView.as_view(), name='subcategories'),
    path('subcategories/create/<int:category_id>', RecordSubCategoryCreateView.as_view(), name='subcategory-create'),
    path('subcategories/delete/<int:category_id>/<int:pk>/', RecordSubCategoryDeleteView.as_view(), name='subcategory-delete'),
    path('subcategories/update/<int:category_id>/<int:pk>/', RecordSubCategoryUpdateView.as_view(), name='subcategory-update'),
    path('ajax/load-subcategories/', load_subcategories, name='ajax_load_subcategories'),

    path('', RecordListView.as_view(), name='records'),
    path('records/create/', RecordCreateView.as_view(), name='records-create'),
    path('records/delete/<int:pk>/', RecordDeleteView.as_view(), name='records-delete'),
    path('records/update/<int:pk>/', RecordUpdateView.as_view(), name='records-update'),
]

urlpatterns.extend(
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

records/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth import get_user_model


class Purpose(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self) -> str:
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = "Record categories"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategory')
    name = models.CharField(max_length=64)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = "Record subcategories"


class Record(models.Model):
    purpose = models.ForeignKey(Purpose, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    sum = models.DecimalField(max_digits=14, decimal_places=2)
    note = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.category}/{self.subcategory} - {self.sum}'

    class Meta:
        verbose_name_plural = "Record categories"

records/forms.py
from django import forms

from records.models import Record, SubCategory


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['purpose', 'type', 'category', 'subcategory', 'sum', 'note']


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['name']

records/views/ajax.py
from django.http import JsonResponse
from records.models import SubCategory


def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = SubCategory.objects.filter(category_id=category_id).values('id', 'name')
    return JsonResponse(list(subcategories), safe=False)

records/views/base.py
from django.apps import apps
from django.forms import modelform_factory
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy


class GenericModelListView(ListView):
    template_name = 'records/item-list.html'
    context_object_name = 'items'
    model_name = None
    item_name = None

    def get_queryset(self):
        if not self.model_name:
            raise ValueError("model_name is not set")
        model = apps.get_model('records', self.model_name)
        return model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_name'] = self.item_name
        context['model_name'] = self.model_name
        context['create_url'] = f"{self.model_name.lower()}-create"
        context['delete_url_name'] = f"{self.model_name.lower()}-delete"
        context['update_url_name'] = f"{self.model_name.lower()}-update"
        return context


class GenericModelCreateView(CreateView):
    template_name = 'records/item-form.html'
    context_object_name = 'items'
    model_name = None
    item_name = None
    reverse_lazy_name = None

    def get_queryset(self):
        model = apps.get_model('records', self.model_name)
        return model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_name'] = self.item_name
        return context

    def get_model(self):
        return apps.get_model('records', self.model_name)

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name)

    def get_form_class(self):
        from django.forms import modelform_factory
        return modelform_factory(self.get_model(), fields='__all__')


class GenericModelDeleteView(DeleteView):
    template_name = 'records/item-delete.html'
    model_name = None
    reverse_lazy_name = None

    def get_object(self, queryset=None):
        model = apps.get_model('records', self.model_name)
        return model.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reverse_lazy_name'] = self.reverse_lazy_name
        return context

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name)


class GenericModelUpdateView(UpdateView):
    template_name = 'records/item-form.html'
    model_name = None
    item_name = None
    reverse_lazy_name = None

    def get_object(self, queryset=None):
        model = apps.get_model('records', self.model_name)
        return model.objects.get(pk=self.kwargs['pk'])

    def get_form_class(self):
        model = apps.get_model('records', self.model_name)
        return modelform_factory(model, fields='__all__')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_name'] = self.item_name
        return context

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name)

records/views/category_views.py
from .base import GenericModelListView, GenericModelCreateView, GenericModelDeleteView, GenericModelUpdateView


class RecordCategoryListView(GenericModelListView):
    model_name = 'Category'
    item_name = 'Категория'


class RecordCategoryCreateView(GenericModelCreateView):
    model_name = 'Category'
    item_name = 'Категория'
    reverse_lazy_name = 'categories'


class RecordCategoryDeleteView(GenericModelDeleteView):
    model_name = 'Category'
    reverse_lazy_name = 'categories'


class RecordCategoryUpdateView(GenericModelUpdateView):
    model_name = 'Category'
    item_name = 'Категория'
    reverse_lazy_name = 'categories'

records/views/purpose_views.py
from .base import GenericModelListView, GenericModelCreateView, GenericModelDeleteView, GenericModelUpdateView


class RecordPurposeListView(GenericModelListView):
    model_name = 'Purpose'
    item_name = 'Статус'


class RecordPurposeCreateView(GenericModelCreateView):
    model_name = 'Purpose'
    item_name = 'Статус'
    reverse_lazy_name = 'purposes'


class RecordPurposeDeleteView(GenericModelDeleteView):
    model_name = 'Purpose'
    reverse_lazy_name = 'purposes'


class RecordPurposeUpdateView(GenericModelUpdateView):
    model_name = 'Purpose'
    item_name = 'Статус'
    reverse_lazy_name = 'purposes'

records/views/record_views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from records.forms import RecordForm
from records.models import Record, Purpose, Category, SubCategory


class RecordListView(ListView):
    model = Record
    template_name = 'records/records-list.html'
    context_object_name = 'records'

    def get_queryset(self):
        qs = super().get_queryset().select_related('purpose', 'category', 'subcategory', 'type')

        purpose_id = self.request.GET.get('purpose')
        category_id = self.request.GET.get('category')
        subcategory_id = self.request.GET.get('subcategory')

        if purpose_id:
            qs = qs.filter(purpose_id=purpose_id)
        if subcategory_id:
            qs = qs.filter(subcategory_id=subcategory_id)
        if category_id:
            qs = qs.filter(category_id=category_id)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'purposes': Purpose.objects.all(),
            'categories': Category.objects.all(),
            'subcategories': SubCategory.objects.all(),
            'selected': {
                'purpose': self.request.GET.get('purpose', ''),
                'category': self.request.GET.get('category', ''),
                'subcategory': self.request.GET.get('subcategory', ''),
            },
        })
        context['delete_url_name'] = "records-delete"
        context['update_url_name'] = "records-update"
        return context


class RecordCreateView(CreateView):
    model = Record
    form_class = RecordForm
    template_name = 'records/records-form.html'
    success_url = reverse_lazy('records')


class RecordUpdateView(UpdateView):
    model = Record
    form_class = RecordForm
    template_name = 'records/records-form.html'
    success_url = reverse_lazy('records')


class RecordDeleteView(DeleteView):
    model = Record
    template_name = 'records/item-delete.html'
    success_url = reverse_lazy('records')
    reverse_lazy_name = 'records'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the URL pattern name (not the URL string)
        context['reverse_lazy_name'] = self.reverse_lazy_name
        return context

records/views/subcategory_views.py
from django.apps import apps
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse

from .base import GenericModelListView, GenericModelCreateView, GenericModelDeleteView, GenericModelUpdateView
from ..models import Category


class RecordSubCategoryListView(GenericModelListView):
    model_name = 'SubCategory'
    item_name = 'Подкатегория'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')

        context['item_name'] = self.item_name
        context['create_url'] = f"{self.model_name.lower()}-create"
        context['delete_url_name'] = f"{self.model_name.lower()}-delete"
        context['update_url_name'] = f"{self.model_name.lower()}-update"

        if category_id:
            category_model = apps.get_model('records', 'Category')
            context['category'] = category_model.objects.filter(pk=category_id).first()

        return context



class RecordSubCategoryCreateView(GenericModelCreateView):
    model_name = 'SubCategory'
    item_name = 'Подкатегория'
    reverse_lazy_name = 'subcategories'

    def dispatch(self, request, *args, **kwargs):
        # Grab the parent category
        self.category = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.category = self.category
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['item_name'] = self.item_name
        return context

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name, kwargs={'category_id': self.category.id})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['category'].initial = self.category
        form.fields['category'].disabled = True
        return form


class RecordSubCategoryDeleteView(GenericModelDeleteView):
    model_name = 'SubCategory'
    item_name = 'Подкатегория'
    reverse_lazy_name = 'subcategories'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['item_name'] = self.item_name
        return context

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name, kwargs={'category_id': self.category.id})


class RecordSubCategoryUpdateView(GenericModelUpdateView):
    model_name = 'SubCategory'
    item_name = 'Подкатегория'
    reverse_lazy_name = 'subcategories'

    def dispatch(self, request, *args, **kwargs):
        # Grab the parent category
        self.category = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.category = self.category
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['item_name'] = self.item_name
        return context

    def get_success_url(self):
        return reverse_lazy(self.reverse_lazy_name, kwargs={'category_id': self.category.id})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['category'].initial = self.category
        form.fields['category'].disabled = True
        return form

records/views/type_views.py
from .base import GenericModelListView, GenericModelCreateView, GenericModelDeleteView, GenericModelUpdateView


class RecordTypeListView(GenericModelListView):
    model_name = 'Type'
    item_name = 'Тип'


class RecordTypeCreateView(GenericModelCreateView):
    model_name = 'Type'
    item_name = 'Тип'
    reverse_lazy_name = 'types'


class RecordTypeDeleteView(GenericModelDeleteView):
    model_name = 'Type'
    reverse_lazy_name = 'types'


class RecordTypeUpdateView(GenericModelUpdateView):
    model_name = 'Type'
    item_name = 'Тип'
    reverse_lazy_name = 'types'

records/templates/records/item-delete.html
{% extends 'records/main.html' %}

{% block title %}Удалить {{ object }}{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Удалить {{ object }}</h1>

    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
        <button type="submit">Удалить</button>
        <a href="{% if category %}{% url reverse_lazy_name category.id %}{% else %}{% url reverse_lazy_name %}{% endif %}">Отмена</a>
    </form>
</div>
{% endblock %}

records/templates/records/item-form.html
{% extends 'records/main.html' %}

{% block title %}Create {{ item_name }}{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>{% if form.instance.pk %}Изменить{% else %}Добавить{% endif %} {{ item_name }}</h2>

        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="error">{{ field.errors.as_text }}</div>
                    {% endif %}
                </div>
            {% endfor %}
            <button class="create-button" type="submit">Save</button>
        </form>
    </div>
{% endblock %}

records/templates/records/item-list.html
{% extends 'records/main.html' %}

{% block content %}
    <div class="container">
        <h1>{{ item_name }}</h1>
        <ul>
            {% for item in items %}
                <li style="display: flex; justify-content: space-between; align-items: center; padding: 0.25em 0; border-bottom: 1px solid #ddd;">
                    <span>{{ item.name }}</span>
                    <span>
                        {% if model_name == 'Category' %}
                            <a class="subcategories-button" href="{% url 'subcategories' item.pk %}">Subcategories</a>
                        {% endif %}
                        {% if item.category_id %}
                            <a class="edit-button" href="{% url update_url_name item.category_id item.pk %}"><i class="fas fa-edit"></i></a>
                            <a class="delete-button" href="{% url delete_url_name item.category_id item.pk %}"><i class="fas fa-trash-alt"></i></a>
                        {% else %}
                            <a class="edit-button" href="{% url update_url_name item.pk %}"><i class="fas fa-edit"></i></a>
                            <a class="delete-button" href="{% url delete_url_name item.pk %}"><i class="fas fa-trash-alt"></i></a>
                        {% endif %}
                    </span>
                </li>
            {% empty %}
                <li>No Items are found.</li>
            {% endfor %}
        </ul>
        <a href="{% if category %}{% url create_url category.id %}{% else %}{% url create_url %}{% endif %}" class="create-button">Create</a>
    </div>
{% endblock %}

records/templates/records/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}DDS{% endblock %}</title>
</head>
<body>
{% include 'records/partials/header.html' %}

<main style="padding: 20px;">
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

records/templates/records/records-form.html
{% extends 'records/main.html' %}

{% block title %}Create Record{% endblock %}

{% block content %}
    <div class="form-container">
        <h1>Create New Record</h1>

        <form method="post">
          {% csrf_token %}

            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <div class="error">{{ field.errors.as_text }}</div>
                {% endif %}
            </div>
            {% endfor %}

          <button class="create-button" type="submit">Save</button>
        </form>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
        $(document).ready(function(){
            $("#id_category").change(function(){
                var url = "{% url 'ajax_load_subcategories' %}";
                var categoryId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                        'category': categoryId
                    },
                    success: function(data){
                        var select = $("#id_subcategory");
                        select.empty();
                        $.each(data, function(index, item){
                            select.append('<option value="' + item.id + '">' + item.name + '</option>');
                        });
                    }
                });
            });
        });
        </script>
    </div>
{% endblock %}

records/templates/records/records-list.html
{% extends 'records/main.html' %}

{% block title %} Cashflow (1) Records {% endblock %}

{% block content %}
    <div class="container">
        <h1>Cashflow Records</h1>

        <a href="{% url 'records-create' %}" class="create-button">Create</a>
        <form method="get" style="margin-bottom: 2rem;">
            <label>
                Purpose:
                <select name="purpose">
                    <option value="">All</option>
                    {% for p in purposes %}
                        <option value="{{ p.id }}" {% if selected.purpose == p.id|stringformat:'s' %}selected{% endif %}>
                            {{ p.name }}
                        </option>
                    {% endfor %}
                </select>
            </label>

            <label>
                Category:
                <select name="category">
                    <option value="">All</option>
                    {% for c in categories %}
                        <option value="{{ c.id }}" {% if selected.category == c.id|stringformat:'s' %}selected{% endif %}>
                            {{ c.name }}
                        </option>
                    {% endfor %}
                </select>
            </label>

            <label>
                Subcategory:
                <select name="subcategory">
                    <option value="">All</option>
                    {% for sc in subcategories %}
                        <option value="{{ sc.id }}" {% if selected.subcategory == sc.id|stringformat:'s' %}selected{% endif %}>
                            {{ sc.name }}
                        </option>
                    {% endfor %}
                </select>
            </label>

            <button type="submit">Filter</button>
        </form>

        <table>
            <thead>
            <tr>
                <th>Date</th>
                <th>Purpose</th>
                <th>Category</th>
                <th>Subcategory</th>
                <th>Sum</th>
                <th>Note</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for record in records %}
                <tr class="{% if record.type.name == "Списание" %}red{% else %}green{% endif %}">
                    <td>{{ record.created_at|date:"d.m.Y" }}</td>
                    <td>{{ record.purpose }}</td>
                    <td>{{ record.category }}</td>
                    <td>{{ record.subcategory }}</td>
                    <td>{{ record.sum }} ₽</td>
                    <td class="note">{{ record.note|default:"—" }}</td>
                    <td>
                        <a class="edit-button" href="{% url 'records-update' record.pk %}">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="delete-button" href="{% url 'records-delete' record.pk %}">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="7" style="text-align: center;">No records found.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}